export const localeText = { noRowsToShow: '조회 결과가 없습니다.', loadingOoo: '조회 중입니다..' };
export const columnDefs = [
    {
        headerName: '번호',
        field: 'boardId',
        width: 50,
        cellStyle: { fontSize: '14px', display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '채널명',
        field: 'chnlNm',
        width: 200,
        cellStyle: { fontSize: '14px', display: 'flex', alignItems: 'center' },
        tooltipField: 'chnlNm',
    },
    {
        headerName: '제목',
        field: 'title',
        width: 100,
        flex: 1,
        tooltipField: 'title',
        cellStyle: { fontSize: '14px', display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '작성자',
        field: 'regName',
        width: 100,
        cellStyle: { fontSize: '14px', display: 'flex', alignItems: 'center' },
        tooltipField: 'regName',
    },
    {
        headerName: '작성일자',
        field: 'regDt',
        width: 150,
        cellStyle: { fontSize: '14px', display: 'flex', alignItems: 'center' },
        tooltipField: 'regDt',
    },
    {
        headerName: '조회',
        field: 'viewCnt',
        width: 80,
        cellStyle: { fontSize: '14px', display: 'flex', alignItems: 'center' },
        tooltipField: 'viewCnt',
    },
];

export const testRows = [
    {
        noticeSeq: 10,
        chName: '뉴요커가 읽어주는 10분 뉴스',
        title: '테스트 공지 사항 제목 10 입니다.',
        regUser: 'ssc001',
        regDt: '2021-02-18 09:00',
        viewCount: 9999,
    },
    {
        noticeSeq: 9,
        chName: '뉴요커가 읽어주는 9분 뉴스',
        title: '테스트 공지 사항 제목 9 입니다.',
        regUser: 'ssc001',
        regDt: '2021-02-18 09:00',
        viewCount: 88888,
    },
    {
        noticeSeq: 8,
        chName: '뉴요커가 읽어주는 8분 뉴스',
        title: '테스트 공지 사항 제목 8 입니다.',
        regUser: 'ssc001',
        regDt: '2021-02-18 09:00',
        viewCount: 77777,
    },
    {
        noticeSeq: 7,
        chName: '뉴요커가 읽어주는 7분 뉴스',
        title: '테스트 공지 사항 제목 7 입니다.',
        regUser: 'ssc001',
        regDt: '2021-02-18 09:00',
        viewCount: 6666,
    },
    {
        noticeSeq: 6,
        chName: '뉴요커가 읽어주는 6분 뉴스',
        title: '테스트 공지 사항 제목 6 입니다.',
        regUser: 'ssc001',
        regDt: '2021-02-18 09:00',
        viewCount: 5555,
    },
    {
        noticeSeq: 5,
        chName: '뉴요커가 읽어주는 5분 뉴스',
        title: '테스트 공지 사항 제목 5 입니다.',
        regUser: 'ssc001',
        regDt: '2021-02-18 09:00',
        viewCount: 1000,
    },
    {
        noticeSeq: 4,
        chName: '뉴요커가 읽어주는 3분 뉴스',
        title: '테스트 공지 사항 제목입니다.',
        regUser: 'ssc001',
        regDt: '2021-02-18 09:00',
        viewCount: 3333,
    },
];
