export default [
    {
        headerName: 'No',
        field: 'linkSeq',
        width: 50,
        cellStyle: { fontSize: '12px', lineHeight: '23px' },
    },
    {
        headerName: '대표이미지',
        field: 'imgUrl',
        cellRenderer: 'imageRenderer',
        cellStyle: { minHeight: '10px', paddingBottom: '1px' },
        autoHeight: false,
        width: 80,
    },
    {
        headerName: '제목',
        field: 'linkTitle',
        tooltipField: 'linkTitle',
        width: 100,
        cellStyle: { fontSize: '12px', lineHeight: '23px' },
        wrapText: true,
        autoHeight: false,
    },
    {
        headerName: 'URL',
        field: 'linkUrl',
        tooltipField: 'linkUrl',
        width: 120,
        cellStyle: { fontSize: '12px', lineHeight: '23px' },
        wrapText: true,
        autoHeight: false,
    },
    {
        headerName: '설명',
        field: 'linkContent',
        tooltipField: 'linkContent',
        width: 140,
        flex: 1,
        cellStyle: { fontSize: '12px', lineHeight: '23px', whiteSpace: 'pre-line' },
        wrapText: true,
        autoHeight: false,
    },
    {
        headerName: '등록자',
        field: 'regId',
        tooltipField: 'regId',
        width: 20,
        flex: 1,
        cellStyle: { fontSize: '12px', lineHeight: '23px', whiteSpace: 'pre-line' },
        wrapText: true,
        autoHeight: false,
    },
    {
        headerName: '등록일',
        field: 'regDt',
        width: 35,
        flex: 1,
        cellStyle: { width: '12px', fontSize: '12px', lineHeight: '23px' },
        wrapText: true,
        autoHeight: false,
    },
    {
        headerName: '수정자',
        field: 'modId',
        tooltipField: 'modId',
        width: 50,
        flex: 1,
        cellStyle: { fontSize: '12px', lineHeight: '23px', whiteSpace: 'pre-line' },
        wrapText: true,
        autoHeight: false,
    },
    {
        headerName: '수정일',
        field: 'modDt',
        width: 40,
        flex: 1,
        cellStyle: { fontSize: '12px', lineHeight: '23px' },
        wrapText: true,
        autoHeight: false,
    },
    {
        headerName: '게재여부',
        field: 'usedYnText',
        cellStyle: { fontSize: '12px', lineHeight: '23px' },
        width: 50,
    },
];
