export const localeText = { noRowsToShow: '조회 결과가 없습니다.', loadingOoo: '조회 중입니다..' };
export const columnDefs = [
    {
        headerName: 'ID',
        field: 'chnlSeq',
        width: 50,
        cellStyle: { fontSize: '12px', display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '개설일',
        field: 'chnlSdt',
        width: 90,
        cellStyle: { fontSize: '12px', display: 'flex', alignItems: 'center' },
        tooltipField: 'chnlSdt',
    },
    {
        headerName: '이미지',
        field: 'chnlThumb',
        width: 90,
        cellRenderer: 'imageRenderer',
        cellStyle: { fontSize: '12px', display: 'flex', alignItems: 'center' },
        // autoHeight: true,
    },
    {
        headerName: '채널명',
        field: 'chnlNm',
        width: 200,
        cellStyle: { fontSize: '12px', display: 'flex', alignItems: 'center' },
        // autoHeight: true,
        tooltipField: 'chnlNm',
    },
    {
        headerName: '설명',
        field: 'chnlMemo',
        width: 80,
        flex: 1,
        // warpText: 1,
        tooltipField: 'chnlMemo',
        autoHeight: true,
        cellStyle: {
            boxSizing: 'border-box',
            whiteSpace: 'normal',
            lineHeight: '20px',
            fontSize: '14px',
            height: '50px',
            display: '-webkit-box',
            paddingTop: '5px',
            '-webkit-line-clamp': 2,
            '-webkit-box-orient': 'vertical',
            overflow: 'hidden',
            cursor: 'pointer',
        },
    },
    {
        headerName: '회차',
        field: 'roundinfo',
        width: 100,
        cellStyle: { fontSize: '12px', display: 'flex', alignItems: 'center' },
        tooltipField: 'roundinfo',
    },
    {
        headerName: '구독',
        field: 'subscribe',
        width: 90,
        cellStyle: { fontSize: '12px', display: 'flex', alignItems: 'center' },
        tooltipField: 'subscribe',
    },
];
