export default [
    {
        headerName: 'NO',
        field: 'letterSeq',
        width: 40,
    },
    {
        headerName: '방법',
        field: 'sendType',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 60,
    },
    {
        headerName: '유형',
        field: 'letterType',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 60,
    },
    {
        headerName: '뉴스레터 명',
        field: 'letterName',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        flex: 1,
    },
    {
        headerName: '발송 시작일',
        field: 'sendStartDt',
        width: 78,
    },
    {
        headerName: '최근 발송일',
        field: 'lastSendDt',
        width: 78,
    },
    {
        headerName: '발송 주기',
        field: 'sendPriod',
        children: [
            { headerName: '일정/콘텐츠', field: 'sendInfo', width: 80 },
            { headerName: '시간', field: 'sendTime', width: 35 },
        ],
    },
    {
        headerName: '구독자 수',
        field: 'subscribeCount',
        width: 65,
    },
    {
        headerName: '상태',
        field: 'status',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 60,
    },
    {
        headerName: '등록일',
        field: 'regDt',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 80,
    },
    {
        headerName: '등록자',
        field: 'regId',
        width: 60,
    },
    {
        headerName: 'A/B TEST',
        field: 'abtestYn',
        width: 65,
        cellRenderer: 'usedYnRenderer',
    },
];
