export const columnDefs = [
    {
        colId: 'checkbox',
        width: 24,
        checkboxSelection: true,
        headerCheckboxSelection: true,
        cellStyle: { display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '신고',
        field: 'declareCnt',
        tooltipField: 'declareCnt',
        width: 60,
        cellStyle: { display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '순번',
        field: 'cmtSeq',
        tooltipField: 'cmtSeq',
        width: 80,
        cellStyle: { display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '댓글내용',
        field: 'cont',
        tooltipField: 'cont',
        flex: 1,
        autoHeight: true,
        resizable: true,
        // suppressDoubleClickExpand: true,
        cellStyle: {
            boxSizing: 'border-box',
            whiteSpace: 'normal',
            lineHeight: '20px',
            fontSize: '14px',
            height: '50px',
            display: '-webkit-box',
            paddingTop: '5px',
            '-webkit-line-clamp': 2,
            '-webkit-box-orient': 'vertical',
            overflow: 'hidden',
            cursor: 'pointer',
        },
    },
    {
        headerName: '이름/ID',
        field: 'userInfo',
        tooltipField: 'userId',
        width: 150,
        cellRenderer: 'userInfoRenderer',
        cellStyle: { display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '등록IP',
        field: 'memIp',
        tooltipField: 'memIp',
        width: 130,
        cellStyle: { display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '계정',
        field: 'memSite',
        tooltipField: 'memSite',
        width: 80,
        cellStyle: { display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '등록일시',
        field: 'regDt',
        tooltipField: 'regDt',
        width: 120,
        cellRenderer: 'dateItemRenderer',
        cellStyle: { display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '상태',
        field: 'statusText',
        tooltipField: 'statusText',
        width: 80,
        cellStyle: { display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '매체',
        field: 'mediaText',
        tooltipField: 'mediaText',
        width: 80,
        cellStyle: { display: 'flex', alignItems: 'center' },
    },
    {
        headerName: '기능',
        field: 'action',
        // tooltipField: 'action',
        width: 80,
        // suppressDoubleClickExpand: true,
        cellRenderer: 'deleteButtonRenderer',
        cellStyle: { display: 'flex', alignItems: 'center', overflow: 'visible' },
    },
];

export const BannedColumnDefs = {
    U: [
        // 차단 ID 관리 목록
        {
            headerName: '',
            colId: 'button',
            width: 60,
            field: 'bannedElement',
            cellRenderer: 'banneButtonRenderer',
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '번호',
            field: 'seqNo',
            tooltipField: 'seqNo',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '아이디',
            field: 'tagValue',
            tooltipField: 'tagValue',
            width: 130,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '계정',
            field: 'tagSource',
            tooltipField: 'tagSource',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '사유',
            field: 'cdNm',
            tooltipField: 'cdNm',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '내용',
            field: 'tagDesc',
            tooltipField: 'tagDesc',
            flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center', height: '50px' },
        },
        {
            headerName: '등록자',
            field: 'regMemberInfo',
            tooltipField: 'regMemberInfo',
            width: 150,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록일시',
            field: 'regDt',
            tooltipField: 'regDt',
            width: 160,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '',
            colId: 'button',
            width: 80,
            field: 'historyInfo',
            cellRenderer: 'historyButtonRenderer',
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
    ],
    I: [
        // 차단 IP 관리 목록
        {
            headerName: '',
            colId: 'button',
            width: 80,
            field: 'bannedElement',
            cellRenderer: 'banneButtonRenderer',
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '번호',
            field: 'seqNo',
            tooltipField: 'seqNo',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록IP',
            field: 'tagValue',
            tooltipField: 'tagValue',
            width: 150,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '사유',
            field: 'cdNm',
            tooltipField: 'cdNm',
            width: 100,
            // flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '내용',
            field: 'tagDesc',
            flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center', height: '50px' },
        },
        {
            headerName: '등록자',
            field: 'regMemberInfo',
            tooltipField: 'regMemberInfo',
            width: 150,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록일시',
            field: 'regDt',
            tooltipField: 'regDt',
            width: 160,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '',
            colId: 'button',
            width: 80,
            field: 'historyInfo',
            cellRenderer: 'historyButtonRenderer',
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
    ],
    W: [
        // 차단 금지어 목록
        {
            headerName: '',
            colId: 'button',
            width: 80,
            field: 'bannedElement',
            cellRenderer: 'banneButtonRenderer',
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '번호',
            field: 'seqNo',
            tooltipField: 'seqNo',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '금지어',
            field: 'tagValue',
            tooltipField: 'tagValue',
            width: 150,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '사유',
            field: 'cdNm',
            tooltipField: 'cdNm',
            width: 100,
            // flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '내용',
            field: 'tagDesc',
            tooltipField: 'tagDesc',
            flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center', height: '50px' },
        },
        {
            headerName: '등록자',
            field: 'regMemberInfo',
            tooltipField: 'regMemberInfo',
            width: 150,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록일시',
            field: 'regDt',
            tooltipField: 'regDt',
            width: 160,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
    ],
};
