export default [
    {
        headerName: 'NO',
        field: 'no',
        width: 40,
    },
    {
        headerName: '방법',
        field: 'title',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 60,
    },
    {
        headerName: '유형',
        field: 'type',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 60,
    },
    {
        headerName: '뉴스레터 명',
        field: 'newsLetter',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        flex: 1,
    },
    {
        headerName: '발송 시작일',
        field: 'startDt',
        width: 78,
    },
    {
        headerName: '최근 발송일',
        field: 'recentDt',
        width: 78,
    },
    {
        headerName: '발송 주기',
        field: 'priod',
        children: [
            { headerName: '일정/콘텐츠', field: 'ct', width: 80 },
            { headerName: '시간', field: 'time', width: 35 },
        ],
    },
    {
        headerName: '구독자 수',
        field: 'subscriber',
        width: 65,
    },
    {
        headerName: '상태',
        field: 'state',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 60,
    },
    {
        headerName: '등록일',
        field: 'regDt',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 80,
    },
    {
        headerName: '등록자',
        field: 'regId',
        width: 60,
    },
    {
        headerName: 'A/B TEST',
        field: 'ab',
        width: 65,
    },
];
