export default [
    {
        headerName: '번호',
        field: 'seqNo',
        cellStyle: { fontSize: '12px' },
        width: 50,
    },
    {
        headerName: '아젠다',
        field: 'agenda',
        cellStyle: { fontSize: '12px' },
        flex: 1,
        tooltipField: 'agenda',
    },
    {
        headerName: '타입',
        field: 'type',
        cellStyle: { fontSize: '12px' },
        width: 40,
    },
    {
        headerName: '등록일',
        field: 'regDate',
        cellStyle: { fontSize: '12px' },
        width: 80,
    },
    {
        headerName: '공개일',
        field: 'openDate',
        cellStyle: { fontSize: '12px' },
        width: 80,
    },
    {
        headerName: '사용여부',
        field: 'usedYn',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '최상단',
        field: 'menu',
        cellStyle: { fontSize: '12px' },
        width: 55,
    },
];

export const rowData = [
    {
        seqNo: '101',
        agenda: '노트르담 대성당',
        type: '일반',
        regDate: '2021-01-02',
        openDate: '2021-01-05',
        usedYn: 'Y',
        menu: 'Y',
    },
    {
        seqNo: '102',
        agenda: '촛불 1년, 그 후',
        type: '일반',
        regDate: '2021-01-07',
        openDate: '2021-01-09',
        usedYn: 'Y',
        menu: 'N',
    },
    {
        seqNo: '103',
        agenda: '중앙정부 업무 지방 이양',
        type: '일반',
        regDate: '2021-01-11',
        openDate: '2021-01-15',
        usedYn: 'Y',
        menu: 'Y',
    },
    {
        seqNo: '104',
        agenda: '산업자본 은행 진출',
        type: '일반',
        regDate: '2021-01-12',
        openDate: '2021-01-16',
        usedYn: 'Y',
        menu: 'N',
    },
    {
        seqNo: '105',
        agenda: '의원소환제',
        type: '일반',
        regDate: '2021-01-17',
        openDate: '2021-01-21',
        usedYn: 'Y',
        menu: 'N',
    },
    {
        seqNo: '106',
        agenda: '집값 안정',
        type: '일반',
        regDate: '2021-01-17',
        openDate: '2021-01-21',
        usedYn: 'Y',
        menu: 'N',
    },
];
