export const localeText = { noRowsToShow: '조회 결과가 없습니다.', loadingOoo: '조회 중입니다..' };
export const columnDefs = [
    {
        headerName: 'ID',
        field: 'epsdSeq',
        width: 35,
        cellStyle: { display: 'flex', alignItems: 'center' },
        tooltipField: 'epsdSeq',
    },
    {
        headerName: '채널명',
        field: 'chnlNm',
        width: 120,
        cellStyle: { display: 'flex', alignItems: 'center' },
        tooltipField: 'chnlNm',
    },
    {
        headerName: '회차',
        field: 'epsdNo',
        width: 50,
        cellStyle: { display: 'flex', alignItems: 'center' },
        tooltipField: 'epsdNo',
    },
    {
        headerName: '에피소드 명',
        field: 'epsdNm',
        width: 120,
        cellStyle: { display: 'flex', alignItems: 'center' },
        tooltipField: 'epsdNm',
    },
    {
        headerName: '설명',
        field: 'epsdMemo',
        flex: 1,
        autoHeight: true,
        cellStyle: {
            boxSizing: 'border-box',
            whiteSpace: 'normal',
            lineHeight: '20px',
            fontSize: '14px',
            height: '50px',
            display: '-webkit-box',
            paddingTop: '5px',
            '-webkit-line-clamp': 2,
            '-webkit-box-orient': 'vertical',
            overflow: 'hidden',
            cursor: 'pointer',
        },
        // tooltipField: 'epsdMemo',
    },
    {
        headerName: '방송일',
        field: 'epsdDate',
        width: 90,
        cellStyle: { display: 'flex', alignItems: 'center' },
        tooltipField: 'epsdDate',
    },
    {
        headerName: '재생시간',
        field: 'playTime',
        width: 70,
        cellStyle: { display: 'flex', alignItems: 'center' },
        tooltipField: 'playTime',
    },
    {
        headerName: '사용',
        field: 'usedYn',
        width: 40,
        cellRenderer: 'usedYnRenderer',
    },
];
