import React from 'react';
import TitleRenderer from './components/TitleRenderer';

export default [
    {
        headerName: '기사ID',
        field: 'totalId',
        width: 80,
        cellStyle: { fontSize: '12px' },
    },
    {
        headerName: '제목 / URL',
        field: 'artTitleUrl',
        width: 450,
        flex: 1,
        autoHeight: true,
        cellStyle: { lineHeight: '18px', height: '60px' },
        cellRendererFramework: (row) => <TitleRenderer {...row} />,
    },
    {
        headerName: '등록일',
        field: 'regDt',
        width: 80,
        cellStyle: { fontSize: '12px' },
    },
    // {
    //     headerName: '사용여부',
    //     field: 'usedYn',
    //     width: 64,
    //     cellStyle: { fontSize: '12px' },
    // },
];

export const test_data = [
    {
        totalId: 23854897,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/15f6f17a-2bf7-4ff6-ac53-ab15f1675ab0.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '결혼 보름만에 사라진 신랑, 시부모도 신혼집도 다 가짜였다',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 21:10:25',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '황선윤',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '지역일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854900,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/b180eacd-08b5-47be-b4d1-d1ffe27416ba.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '징계위 열린 날, 윤석열은 40년 절친 보내며 소주잔 기울였다',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 21:06:25',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '박태인',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854896,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/b361199b-49da-4f73-9f9d-2d2e608ccf86.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '스페이스X 우주선 시제품 착륙중 폭발···머스크 "데이터 얻어"',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 21:03:43',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '함민정',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'Y',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854895,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/15ec4652-922f-442a-b40b-128caec605b2.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '공정거래법 통과로…SK텔레콤 중간지주 전환 속도 붙는다',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 21:00:00',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '박형수',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '경제일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854898,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/ae6ef03e-9497-4ebf-891d-669982cc7bb9.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '교육부, 동서대 총장 고발…법인부담금 교비에서 부당 지급',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 20:48:58',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '남윤서',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '교육일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854893,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'G',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/b3a0000f-a78f-483b-9acb-badaf9d47bf4.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '&#91;타임라인&#93;尹 운명의 날 음모와 반전…19금 드라마 뺨친 16일의 기록',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 20:43:56',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '조문규.나운채',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '판결·판례',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854899,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/80b28eda-1d05-4bc6-8bd1-29cffd24df09.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '문 대통령 “탄소중립 추진”…흑백 화면엔 “무서웠다” 평가도',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 20:43:34',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '윤성민',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '정치일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854894,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'T',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/69bee182-e0a1-4f38-b857-5da2d35c05e3.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '&#91;LIVE&#93;윤석열 운명의 날...秋, 尹 기나긴 하루',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 20:42:52',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '조문규',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '청와대일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854902,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/bca9e4d2-72e3-4a67-85df-6d9f024f1349.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: "현대차, '로봇 개' 보스턴 다이내믹스 인수 가시화",
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 20:39:22',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '이동현',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'Y',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '경제일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854903,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/ffecd1f3-8af3-46f2-8c59-0e47491353d0.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '"별 거지 같은…" 여성전용 주차장에 댄 차 타고 떠난 주진우',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 20:36:42',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '배재성',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854904,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/284344c2-12fa-4df3-85e7-8bcf92c7145b.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '&#91;오병상의 코멘터리&#93;공수처 충격..지리멸렬 국민의힘',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 20:36:20',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '오병상',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '칼럼',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854901,
        sourceCode: '3',
        sourceName: '중앙일보(집배신)',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/htmlphoto_mmdata/202012/10/69bee182-e0a1-4f38-b857-5da2d35c05e3.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '&#91;속보&#93;尹징계위 9시간 30분만에 오늘 심의 종료…15일 속행',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 20:35:43',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '배재성',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'Y',
        contentKorname: '판결·판례',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854891,
        sourceCode: 'l1',
        sourceName: 'Join:D',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/joind_news/202101/08/1607564991110U3aN6.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '차이, 700억원 규모 시리즈 B 투자 유치',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 10:49:51',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'N',
        contentKorname: '경제일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854886,
        sourceCode: 'l1',
        sourceName: 'Join:D',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/joind_news/202012/21/1607564991110U3aN6.jpg.tn_120.jpg',
        artGroupNum: '',
        artTitle: '차이, 700억원 규모 시리즈 B 투자 유치',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 10:49:51',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'N',
        contentKorname: null,
        serviceFlag: 'Y',
    },
    {
        totalId: 23854885,
        sourceCode: 'l1',
        sourceName: 'Join:D',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/joind_news/202012/21/1607561797314r4Prb.PNG.tn_120.jpg',
        artGroupNum: '',
        artTitle: '[시황] 1BTC, 1.8만$ 라인 사수..레이달리오도 긍정 반응',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 09:57:42',
        artModDt: null,
        deskingYn: 'N',
        artReporter: '강기헌.홍길동',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'N',
        contentKorname: '경제일반',
        serviceFlag: 'Y',
    },
    {
        totalId: 23854884,
        sourceCode: 'l1',
        sourceName: 'Join:D',
        artType: 'B',
        artTypeName: null,
        artThumb: '/news/component/joind_news/202012/21/1607432226118CT0Kl.png.tn_120.jpg',
        artGroupNum: '',
        artTitle: '&#91;권인욱&#93; 가상화폐 증여의 거의 모든 것',
        pressPan: '',
        pressMyun: '',
        serviceDaytime: '2020-12-10 01:37:39',
        artModDt: '2020-12-21 10:49:54',
        deskingYn: 'N',
        artReporter: '',
        ovpYn: 'N',
        ovpLink: null,
        youtubeYn: 'N',
        artJamTitle: null,
        artJamMobTitle: null,
        artEditTitle: null,
        artEditMobTitle: null,
        bulkflag: 'N',
        contentKorname: '경제일반',
        serviceFlag: 'Y',
    },
];
