export default [
    {
        headerName: '기자번호',
        field: 'repSeqText',
        width: 65,
        cellStyle: { lineHeight: '43px', whiteSpace: 'pre-wrap' },
    },
    {
        headerName: '타입코드',
        field: 'jplusRelDivNm',
        width: 63,
        cellStyle: { lineHeight: '43px' },
    },
    {
        headerName: '사진',
        field: 'profilePhoto',
        width: 50,
        cellRenderer: 'circleImageRenderer',
        cellStyle: { padding: '3px 6px' },
    },
    {
        headerName: '기자이름',
        field: 'columnistNm',
        width: 70,
        cellStyle: { lineHeight: '43px' },
    },
    {
        headerName: '이메일',
        field: 'email',
        width: 160,
        flex: 1,
        tooltipField: 'email',
        cellStyle: { lineHeight: '43px' },
    },
    {
        headerName: '약력정보',
        field: 'profile',
        tooltipField: 'profile',
        width: 160,
        flex: 1,
        cellStyle: { lineHeight: '43px' },
    },
    {
        headerName: '등록자',
        field: 'regMember',
        tooltipField: 'regMember',
        width: 130,
        cellStyle: { lineHeight: '43px' },
    },
    {
        headerName: '등록일',
        field: 'regDt',
        width: 130,
        cellStyle: { lineHeight: '43px' },
    },
    {
        headerName: '사용',
        field: 'status',
        width: 40,
        cellRenderer: 'usedYnRenderer',
    },
];
