export const columnDefs = [
    {
        headerName: '에피소드명',
        field: 'title',
        width: 200,
        cellStyle: { paddingTop: '5px', paddingBottom: '5px', display: 'flex', alignItems: 'center', lineHeight: '18px' },
        tooltipField: 'title',
        wrapText: true,
        autoHeight: true,
    },
    {
        headerName: '게시일',
        field: 'crtDt',
        width: 90,
        cellStyle: { display: 'flex', alignItems: 'center', lineHeight: '18px' },
        tooltipField: 'crtDt',
    },
    {
        headerName: '제작자',
        field: 'author',
        width: 80,
        cellStyle: { display: 'flex', alignItems: 'center' },
        tooltipField: 'author',
    },
    {
        headerName: '소개',
        field: 'summary',
        flex: 1,
        cellStyle: { display: 'flex', alignItems: 'center', lineHeight: '18px', paddingTop: '5px', paddingBottom: '5px' },
        tooltipField: 'summary',
        wrapText: true,
        autoHeight: true,
    },
    {
        headerName: '보기',
        field: '이동',
        width: 58,
        cellRenderer: 'buttonRenderer',
    },
];
