export default [
    {
        headerName: '분류',
        field: 'type',
        cellStyle: { fontSize: '12px' },
        flex: 1,
    },
    {
        headerName: '30초',
        field: 'ths',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '1분',
        field: 'om',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '2분',
        field: 'tm',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '5분',
        field: 'fim',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '10분',
        field: 'tem',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '20분',
        field: 'twm',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '30분',
        field: 'thm',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '60분',
        field: 'sim',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '12시간',
        field: 'twh',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
    {
        headerName: '1일',
        field: 'day',
        cellStyle: { fontSize: '12px' },
        width: 65,
    },
];

export const rowData = [
    {
        type: '중앙1',
        ths: '2개,0초',
        om: '5개,1초',
        tm: '6개,4초',
        fim: '29개,10초',
        tem: '37개,16초',
        twm: '10개,8초',
        thm: '1개,0초',
        sim: '8개,7초',
        twh: '1개,0초',
        day: '',
    },
    {
        type: '중앙2',
        ths: '1개,0초',
        om: '',
        tm: '1개,0초',
        fim: '',
        tem: '2개,1초',
        twm: '1개,0초',
        thm: '1개,0초',
        sim: '1개,0초',
        twh: '2개,0초',
        day: '',
    },
    {
        type: '중앙3',
        ths: '',
        om: '5개,0초',
        tm: '4개,1초',
        fim: '5개,2초',
        tem: '4개,1초',
        twm: '',
        thm: '',
        sim: '1개,0초',
        twh: '',
        day: '1개,0초',
    },
    {
        type: '중앙4',
        ths: '1개,0초',
        om: '19개,17초',
        tm: '2개,1초',
        fim: '16개,4초',
        tem: '2개,3초',
        twm: '',
        thm: '',
        sim: '',
        twh: '',
        day: '',
    },
    {
        type: '포털1',
        ths: '2개,0초',
        om: '5개,1초',
        tm: '6개,4초',
        fim: '29개,10초',
        tem: '37개,16초',
        twm: '10개,8초',
        thm: '1개,0초',
        sim: '8개,7초',
        twh: '1개,0초',
        day: '',
    },
    {
        type: '포털2',
        ths: '1개,0초',
        om: '',
        tm: '1개,0초',
        fim: '',
        tem: '2개,1초',
        twm: '1개,0초',
        thm: '1개,0초',
        sim: '1개,0초',
        twh: '2개,0초',
        day: '',
    },
    {
        type: '포털3',
        ths: '',
        om: '5개,0초',
        tm: '4개,1초',
        fim: '5개,2초',
        tem: '4개,1초',
        twm: '',
        thm: '',
        sim: '1개,0초',
        twh: '',
        day: '1개,0초',
    },
    {
        type: '포털4',
        ths: '1개,0초',
        om: '19개,17초',
        tm: '2개,1초',
        fim: '16개,4초',
        tem: '2개,3초',
        twm: '',
        thm: '',
        sim: '',
        twh: '',
        day: '',
    },
    {
        type: '포털5',
        ths: '2개,0초',
        om: '5개,1초',
        tm: '6개,4초',
        fim: '29개,10초',
        tem: '37개,16초',
        twm: '10개,8초',
        thm: '1개,0초',
        sim: '8개,7초',
        twh: '1개,0초',
        day: '',
    },
    {
        type: '기타1',
        ths: '1개,0초',
        om: '',
        tm: '1개,0초',
        fim: '',
        tem: '2개,1초',
        twm: '1개,0초',
        thm: '1개,0초',
        sim: '1개,0초',
        twh: '2개,0초',
        day: '',
    },
    {
        type: '기타2',
        ths: '',
        om: '5개,0초',
        tm: '4개,1초',
        fim: '5개,2초',
        tem: '4개,1초',
        twm: '',
        thm: '',
        sim: '1개,0초',
        twh: '',
        day: '1개,0초',
    },
    {
        type: '기타3',
        ths: '1개,0초',
        om: '19개,17초',
        tm: '2개,1초',
        fim: '16개,4초',
        tem: '2개,3초',
        twm: '',
        thm: '',
        sim: '',
        twh: '',
        day: '',
    },
    {
        type: '기타4',
        ths: '2개,0초',
        om: '5개,1초',
        tm: '6개,4초',
        fim: '29개,10초',
        tem: '37개,16초',
        twm: '10개,8초',
        thm: '1개,0초',
        sim: '8개,7초',
        twh: '1개,0초',
        day: '',
    },
    {
        type: '기타5',
        ths: '1개,0초',
        om: '',
        tm: '1개,0초',
        fim: '',
        tem: '2개,1초',
        twm: '1개,0초',
        thm: '1개,0초',
        sim: '1개,0초',
        twh: '2개,0초',
        day: '',
    },
    {
        type: '기타6',
        ths: '',
        om: '5개,0초',
        tm: '4개,1초',
        fim: '5개,2초',
        tem: '4개,1초',
        twm: '',
        thm: '',
        sim: '1개,0초',
        twh: '',
        day: '1개,0초',
    },
    {
        type: '기타7',
        ths: '1개,0초',
        om: '19개,17초',
        tm: '2개,1초',
        fim: '16개,4초',
        tem: '2개,3초',
        twm: '',
        thm: '',
        sim: '',
        twh: '',
        day: '',
    },
];
