export default [
    {
        headerName: 'NO',
        field: 'no',
        width: 40,
    },
    {
        headerName: '유형',
        field: 'type',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 60,
    },
    {
        headerName: '뉴스레터 명',
        field: 'newsLetter',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 100,
    },
    {
        headerName: '제목',
        field: 'title',
        flex: 1,
    },
    {
        headerName: '발송일',
        field: 'sendDt',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 120,
    },
    {
        headerName: '전체 발송\n건수',
        field: 'sendTotal',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 100,
    },
    {
        headerName: '발송 결과',
        field: 'sendResult',
        children: [{ headerName: '성공률', field: 'successRate', width: 75 }],
    },
    {
        headerName: '오픈 결과',
        field: 'openResult',
        children: [{ headerName: '오픈률', field: 'openRate', width: 75 }],
    },
    {
        headerName: '클릭 결과',
        field: 'clickResult',
        children: [{ headerName: '클릭률', field: 'clickRate', width: 75 }],
    },
    {
        headerName: '상태',
        field: 'state',
        sortable: true,
        unSortIcon: true,
        sort: null,
        sortingOrder: ['asc', 'desc'],
        width: 70,
    },
    {
        headerName: 'A/B TEST',
        field: 'ab',
        width: 70,
    },
];
