export const localeText = { noRowsToShow: '조회 결과가 없습니다.', loadingOoo: '조회 중입니다..' };

export const columnDefs = {
    id: [
        {
            headerName: '',
            colId: 'button',
            width: 80,
            field: 'bannedYn',
            cellRenderer: 'BanneButtonRenderer',
            // checkboxSelection: true,
            // suppressMenu: true,
            // headerCheckboxSelection: true,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: 'IDX',
            field: 'commentSeq',
            tooltipField: 'commentSeq',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '아이디',
            field: 'commentId',
            tooltipField: 'commentId',
            width: 130,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '계정',
            field: 'source',
            tooltipField: 'source',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '사유',
            field: 'reason',
            tooltipField: 'reason',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '내용',
            field: 'content',
            width: 300,
            flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록자',
            field: 'regId',
            tooltipField: 'regId',
            width: 150,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록일시',
            field: 'regDt',
            tooltipField: 'regDt',
            width: 160,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
    ],
    ip: [
        {
            headerName: '',
            colId: 'button',
            width: 80,
            field: 'bannedYn',
            cellRenderer: 'BanneButtonRenderer',
            // checkboxSelection: true,
            // suppressMenu: true,
            // headerCheckboxSelection: true,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: 'IDX',
            field: 'commentSeq',
            tooltipField: 'commentSeq',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록ip',
            field: 'regIp',
            tooltipField: 'regIp',
            width: 150,
            // cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '사유',
            field: 'reason',
            tooltipField: 'reason',
            width: 100,
            // flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '내용',
            field: 'content',
            width: 300,
            flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록자',
            field: 'regId',
            tooltipField: 'regId',
            width: 150,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록일시',
            field: 'regDt',
            tooltipField: 'regDt',
            width: 160,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
    ],
    word: [
        {
            headerName: '',
            colId: 'button',
            width: 80,
            field: 'bannedYn',
            cellRenderer: 'BanneButtonRenderer',
            // checkboxSelection: true,
            // suppressMenu: true,
            // headerCheckboxSelection: true,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: 'IDX',
            field: 'commentSeq',
            tooltipField: 'commentSeq',
            width: 100,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '금지어',
            field: 'word',
            tooltipField: 'word',
            width: 150,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '사유',
            field: 'reason',
            tooltipField: 'reason',
            width: 100,
            // flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '내용',
            field: 'content',
            width: 300,
            flex: 1,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록자',
            field: 'regId',
            tooltipField: 'regId',
            width: 150,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
        {
            headerName: '등록일시',
            field: 'regDt',
            tooltipField: 'regDt',
            width: 160,
            cellStyle: { display: 'flex', alignItems: 'center' },
        },
    ],
};
