import React from 'react';
import AppendButton from '../components/ComponentAppendButton';
import LinkButton from '../components/ComponentLinkButton';

export const columnDefs = [
    {
        headerName: 'ID',
        field: 'componentSeq',
        width: 40,
    },
    {
        headerName: '컴포넌트명',
        field: 'componentName',
        // cellClass: 'ag-cell-center',
        // cellStyle: { textAlign: 'center' },
        width: 190,
    },
    {
        headerName: '위치그룹',
        field: 'tpZone',
        width: 70,
        cellStyle: { textAlign: 'center' },
    },
    {
        headerName: '',
        field: 'append',
        width: 40,
        cellStyle: { textAlign: 'center' },
        cellRendererFramework: (params) => <AppendButton {...params} />,
    },
    {
        headerName: '',
        field: 'link',
        width: 40,
        cellStyle: { textAlign: 'center' },
        cellRendererFramework: (params) => <LinkButton {...params} />,
    },
];

export const rowData = [
    {
        componentSeq: 162,
        componentName: '메인 실시간 뉴스',
        tpZone: '상단영역',
        useYn: null,
        templateSeq: 124,
        relOrder: 1,
    },
    {
        componentSeq: 143,
        componentName: '메인_헤드라인뉴스_컴포넌트',
        tpZone: '상단영역',
        useYn: null,
        templateSeq: 125,
        relOrder: 2,
    },
    {
        componentSeq: 166,
        componentName: '메인_이슈별뉴스_컴포넌트',
        tpZone: '상단영역',
        useYn: null,
        templateSeq: 136,
        relOrder: 3,
    },
    {
        componentSeq: 148,
        componentName: '메인_주요뉴스 01_컴포넌트',
        tpZone: '상단영역',
        useYn: null,
        templateSeq: 139,
        relOrder: 4,
    },
    {
        componentSeq: 150,
        componentName: '메인_오피니언_사설',
        tpZone: '상단영역',
        useYn: null,
        templateSeq: 142,
        relOrder: 5,
    },
    {
        componentSeq: 151,
        componentName: '메인_오피니언_칼럼',
        tpZone: '상단영역',
        useYn: null,
        templateSeq: 144,
        relOrder: 6,
    },
    {
        componentSeq: 154,
        componentName: '메인_연재',
        tpZone: '상단영역',
        useYn: null,
        templateSeq: 150,
        relOrder: 7,
    },
    {
        componentSeq: 160,
        componentName: '메인_주요뉴스02',
        tpZone: '상단영역',
        useYn: null,
        templateSeq: 158,
        relOrder: 8,
    },
    {
        componentSeq: 155,
        componentName: '메인_스포츠',
        tpZone: '메인영역',
        useYn: null,
        templateSeq: 151,
        relOrder: 9,
    },
    {
        componentSeq: 157,
        componentName: '메인_부동산',
        tpZone: '메인영역',
        useYn: null,
        templateSeq: 153,
        relOrder: 10,
    },
    {
        componentSeq: 158,
        componentName: '메인_문화',
        tpZone: '상단영역',
        useYn: null,
        templateSeq: 180,
        relOrder: 11,
    },
    {
        componentSeq: 159,
        componentName: '메인_전국실시간 뉴스',
        tpZone: '메인영역',
        useYn: null,
        templateSeq: 155,
        relOrder: 12,
    },
    {
        componentSeq: 152,
        componentName: '메인_TV_비주얼',
        tpZone: '하단영역',
        useYn: null,
        templateSeq: 143,
        relOrder: 13,
    },
    {
        componentSeq: 149,
        componentName: '메인_날씨',
        tpZone: '하단영역',
        useYn: null,
        templateSeq: 141,
        relOrder: 14,
    },
    {
        componentSeq: 147,
        componentName: '메인_랭킹뉴스',
        tpZone: '하단영역',
        useYn: null,
        templateSeq: 138,
        relOrder: 15,
    },
    {
        componentSeq: 146,
        componentName: '메인_그래픽',
        tpZone: '하단영역',
        useYn: null,
        templateSeq: 137,
        relOrder: 16,
    },
];
