import React from 'react';
import AppendButton from '../components/TemplateAppendButton';
import LinkButton from '../components/TemplateLinkButton';

export const columnDefs = [
    {
        headerName: 'ID',
        field: 'templateSeq',
        width: 50,
    },
    {
        headerName: '템플릿명',
        field: 'templateName',
        // cellClass: 'ag-cell-center',
        // cellStyle: { textAlign: 'center' },
        width: 190,
    },
    {
        headerName: '위치그룹',
        field: 'tpZone',
        width: 70,
        cellStyle: { textAlign: 'center' },
    },
    {
        headerName: '',
        field: 'append',
        width: 40,
        cellStyle: { textAlign: 'center' },
        cellRendererFramework: (params) => <AppendButton {...params} />,
    },
    {
        headerName: '',
        field: 'link',
        width: 40,
        cellStyle: { textAlign: 'center' },
        cellRendererFramework: (params) => <LinkButton {...params} />,
    },
];

export const rowData = [
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 123,
        templateName: '메인_ 헤더및 네비',
        templateWidth: 1100,
        templateThumbnail: null,
        tpZone: '상단영역',
        useYn: null,
        relOrder: 1,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 124,
        templateName: '메인 실시간 뉴스',
        templateWidth: 1920,
        templateThumbnail: null,
        tpZone: '상단영역',
        useYn: null,
        relOrder: 2,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 125,
        templateName: '메인_헤드라인뉴스',
        templateWidth: 1100,
        templateThumbnail: '/image/template/1003/125.png',
        tpZone: '상단영역',
        useYn: null,
        relOrder: 3,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 134,
        templateName: '메인_코로나배너',
        templateWidth: 1920,
        templateThumbnail: null,
        tpZone: '상단영역',
        useYn: null,
        relOrder: 4,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 136,
        templateName: '메인_이슈별뉴스',
        templateWidth: 1100,
        templateThumbnail: null,
        tpZone: '상단영역',
        useYn: null,
        relOrder: 5,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 139,
        templateName: '메인_주요뉴스 01',
        templateWidth: 460,
        templateThumbnail: null,
        tpZone: '상단영역',
        useYn: null,
        relOrder: 6,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 142,
        templateName: '메인_오피니언_사설',
        templateWidth: 290,
        templateThumbnail: null,
        tpZone: '상단영역',
        useYn: null,
        relOrder: 7,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 144,
        templateName: '메인_오피니언_칼럼',
        templateWidth: 290,
        templateThumbnail: null,
        tpZone: '상단영역',
        useYn: null,
        relOrder: 8,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 150,
        templateName: '메인_연재',
        templateWidth: 1100,
        templateThumbnail: '/image/template/1003/150.png',
        tpZone: '상단영역',
        useYn: null,
        relOrder: 9,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 158,
        templateName: '메인_주요뉴스02',
        templateWidth: 460,
        templateThumbnail: null,
        tpZone: '상단영역',
        useYn: null,
        relOrder: 10,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 151,
        templateName: '메인_스포츠_좌측',
        templateWidth: 278,
        templateThumbnail: '/image/template/1003/151.png',
        tpZone: '메인영역',
        useYn: null,
        relOrder: 11,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 152,
        templateName: '메인_이슈키워드',
        templateWidth: 274,
        templateThumbnail: '/image/template/1003/152.png',
        tpZone: '메인영역',
        useYn: null,
        relOrder: 12,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 153,
        templateName: '메인_부동산',
        templateWidth: 580,
        templateThumbnail: null,
        tpZone: '메인영역',
        useYn: null,
        relOrder: 13,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 180,
        templateName: '메인_문화',
        templateWidth: 580,
        templateThumbnail: null,
        tpZone: '상단영역',
        useYn: null,
        relOrder: 14,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 155,
        templateName: '메인_전국실시간뉴스',
        templateWidth: 580,
        templateThumbnail: null,
        tpZone: '메인영역',
        useYn: null,
        relOrder: 15,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 143,
        templateName: '메인_TV_비주얼',
        templateWidth: 1440,
        templateThumbnail: null,
        tpZone: '하단영역',
        useYn: null,
        relOrder: 16,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 141,
        templateName: '메인_날씨',
        templateWidth: 342,
        templateThumbnail: null,
        tpZone: '하단영역',
        useYn: null,
        relOrder: 17,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 140,
        templateName: '메인_운세',
        templateWidth: 725,
        templateThumbnail: null,
        tpZone: '하단영역',
        useYn: null,
        relOrder: 18,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 138,
        templateName: '메인_랭킹뉴스',
        templateWidth: 735,
        templateThumbnail: null,
        tpZone: '하단영역',
        useYn: null,
        relOrder: 19,
    },
    {
        servicePlatform: 'P',
        domainId: '1003',
        domainName: '서울시스템',
        templateSeq: 137,
        templateName: '메인_그래픽',
        templateWidth: 326,
        templateThumbnail: null,
        tpZone: '하단영역',
        useYn: null,
        relOrder: 20,
    },
];
