import React from 'react';
import { ListTitleRenderer, ImageRenderer, IArticleStatusRenderer, SendStatusRenderer } from './GirdRenderer';

export const tempColumnDefs = [
    {
        headerName: 'ID',
        field: 'repId',
        width: 50,
        cellStyle: { fontSize: '12px', lineHeight: '23px', paddingTop: '22px' },
    },
    {
        headerName: '\t출처',
        field: 'source',
        width: 100,
        cellStyle: { fontSize: '12px', lineHeight: '23px', paddingTop: '22px', paddingLeft: '12px' },
    },
    {
        headerName: '\t출고일',
        field: 'listOutDate',
        width: 100,
        cellStyle: { fontSize: '12px', lineHeight: '23px', paddingTop: '22px', paddingLeft: '12px' },
    },
    {
        headerName: '\t이미지',
        field: 'listRepImg',
        cellRendererFramework: (params) => <ImageRenderer {...params} />,
        width: 100,
        cellStyle: { fontSize: '12px', lineHeight: '23px', paddingTop: '8px' },
    },
    {
        headerName: '\t\t\t\t\t기사제목\n\t\t\t\t\tSNS제목',
        field: 'listTitle',
        wrapText: true,
        width: 300,
        flex: true,
        cellRendererFramework: (params) => <ListTitleRenderer {...params} />,
        cellStyle: { fontSize: '12px', lineHeight: '40px' },
    },
    {
        headerName: '\t전송상태',
        field: 'listOutStatus',
        width: 150,
        cellRendererFramework: (params) => <SendStatusRenderer {...params} />,
        cellStyle: { fontSize: '12px', lineHeight: '23px' },
    },
    {
        headerName: '\t\tFB InstantArticle\n상태\t\t\t전송일\t\t\t전송',
        field: 'listArticleStatus',
        width: 250,
        cellRendererFramework: (params) => <IArticleStatusRenderer {...params} />,
        cellStyle: { fontSize: '12px', lineHeight: '23px' },
    },
];

export const tempRowData = [
    {
        repId: 1000,
        source: '중앙선데이(조판)',
        outDate: '2020-11-25 13:44:06',
        repImg: 'http://pds.joins.com/news/search_direct_link/000.jpg',
        newflag: false,
        articleTitle: `"시그널·비숲과 달라"..'낮과 밤' 믿고보는 남궁민, 살인 추리극도 홈런 칠까(종합)'`,
        snsTitle: `"시그널·비숲과 달라"..'낮과 밤' 믿고보는 남궁민, 살인 추리극도 홈런 칠까(종합)'`,
        reservation: true,
        insStatus: 'N',
        sendDate: '2020-11-25 13:40:05',
        sendFlag: 'N',
        facebook: 'N',
        twitter: 'N',
    },
    {
        repId: 999,
        source: '중앙선데이(조판)',
        outDate: '2020-10-25 13:40:05',
        repImg: 'http://pds.joins.com/news/search_direct_link/000.jpg',
        newflag: true,
        articleTitle: `'펜트' 뛰는 놈 위에 나는 이지아, 아무도 못 이기네`,
        snsTitle: `'펜트' 뛰는 놈 위에 나는 이지아, 아무도 못 이기네`,
        reservation: false,
        insStatus: 'Y',
        sendDate: '2020-10-25 13:40:05',
        sendFlag: 'Y',
        facebook: 'N',
        twitter: 'Y',
    },
    {
        repId: 998,
        source: '중앙선데이(조판)',
        outDate: '2020-10-25 13:40:05',
        repImg: 'http://pds.joins.com/news/search_direct_link/000.jpg',
        newflag: false,
        articleTitle: `"그동안 쌓인 감정을 터뜨린 기분" 박신혜의 이유있는 선택`,
        snsTitle: `"그동안 쌓인 감정을 터뜨린 기분" 박신혜의 이유있는 선택`,
        reservation: true,
        insStatus: 'Y',
        sendDate: '2020-10-25 13:40:05',
        sendFlag: 'Y',
        facebook: 'Y',
        twitter: 'N',
    },
    {
        repId: 998,
        source: '중앙선데이(조판)',
        outDate: '2020-10-25 13:40:05',
        repImg: 'http://pds.joins.com/news/search_direct_link/000.jpg',
        newflag: true,
        articleTitle: `"그동안 쌓인 감정을 터뜨린 기분" 박신혜의 이유있는 선택`,
        snsTitle: `"그동안 쌓인 감정을 터뜨린 기분" 박신혜의 이유있는 선택`,
        insStatus: 'Y',
        sendDate: '2020-10-25 13:40:05',
        sendFlag: 'Y',
        facebook: 'Y',
        twitter: 'Y',
    },
];
