export default [
    {
        headerName: '매체',
        field: 'source',
        width: 100,
        cellStyle: { fontSize: '12px' },
    },
    {
        headerName: '기사 번호',
        field: 'seqNo',
        width: 100,
        cellStyle: { fontSize: '12px' },
    },
    {
        headerName: '기사 제목',
        field: 'title',
        cellStyle: { fontSize: '12px' },
        flex: 1,
    },
    {
        headerName: '기사 IUD',
        field: 'iud',
        width: 100,
        cellStyle: { fontSize: '12px' },
    },
    {
        headerName: 'loader',
        field: 'loader',
        width: 100,
        cellStyle: { fontSize: '12px' },
    },
    {
        headerName: 'dump',
        field: 'dump',
        width: 100,
        cellStyle: { fontSize: '12px' },
    },

    {
        headerName: 'sender',
        field: 'sender',
        cellStyle: { fontSize: '12px' },
        children: [
            {
                headerName: '네이버',
                field: 'naver',
                width: 100,
                cellStyle: { fontSize: '12px' },
            },
            {
                headerName: '다음',
                field: 'daum',
                width: 100,
                cellStyle: { fontSize: '12px' },
            },
            {
                headerName: '네이트',
                field: 'nate',
                width: 100,
                cellStyle: { fontSize: '12px' },
            },
            {
                headerName: '줌',
                field: 'zoom',
                width: 100,
                cellStyle: { fontSize: '12px' },
            },
        ],
    },
];

export const rowData = [
    {
        source: '중앙일보',
        seqNo: '70800',
        title: '테스트 기사 제목',
        IUD: 'I',
        loader: '대기',
        dump: '대기',
        naver: '대기',
        daum: '대기',
        nate: '대기',
        zoom: '대기',
    },
    {
        source: '선데이',
        seqNo: '70799',
        title: '테스트 기사 제목',
        IUD: 'U',
        loader: '완료\n(2021-01-07 14:14:32)',
        dump: '완료\n(2021-01-07 14:14:32)',
        naver: '대기',
        daum: '완료\n(2021-01-07 14:14:32)',
        nate: '완료\n(2021-01-07 14:14:32)',
        zoom: '대기',
    },
    {
        source: '일간',
        seqNo: '70798',
        title: '테스트 기사 제목',
        IUD: 'I',
        loader: '대기',
        dump: '대기',
        naver: '대기',
        daum: '대기',
        nate: '대기',
        zoom: '대기',
    },
    {
        source: '중앙데일리',
        seqNo: '70564',
        title: '테스트 기사 제목',
        IUD: 'U',
        loader: '완료\n(2021-01-10 14:14:32)',
        dump: '완료\n(2021-01-10 14:14:32)',
        naver: '완료\n(2021-01-10 14:14:32)',
        daum: '완료\n(2021-01-10 14:14:32)',
        nate: '대기',
        zoom: '대기',
    },
    {
        source: '중앙일보',
        seqNo: '70135',
        title: '테스트 기사 제목',
        IUD: 'I',
        loader: '대기',
        dump: '대기',
        naver: '완료\n(2021-01-10 17:11:10)',
        daum: '대기',
        nate: '대기',
        zoom: '대기',
    },
    {
        source: '선데이',
        seqNo: '70647',
        title: '테스트 기사 제목',
        IUD: 'I',
        loader: '대기',
        dump: '대기',
        naver: '완료\n(2021-01-09 15:14:32)',
        daum: '실패',
        nate: '대기',
        zoom: '완료\n(2021-01-09 15:14:32)',
    },
    {
        source: '일간',
        seqNo: '70670',
        title: '테스트 기사 제목',
        IUD: 'I',
        loader: '완료\n(2021-01-18 17:18:08)',
        dump: '대기',
        naver: '대기',
        daum: '대기',
        nate: '실패',
        zoom: '실패',
    },
    {
        source: '중앙데일리',
        seqNo: '70501',
        title: '테스트 기사 제목',
        IUD: 'I',
        loader: '완료\n(2021-01-15 16:17:21)',
        dump: '대기',
        naver: '대기',
        daum: '실패',
        nate: '실패',
        zoom: '완료\n(2021-01-15 16:15:23)',
    },
];
