import React from 'react';
import RcvProgsRenderer from './components/RcvProgsRenderer';

export default [
    {
        headerName: '매체',
        field: 'source',
        width: 100,
        cellStyle: { fontSize: '12px' },
    },
    {
        headerName: '기사 번호',
        field: 'seqNo',
        width: 100,
        cellStyle: { fontSize: '12px' },
    },
    {
        headerName: '기사 제목',
        wrapText: true,
        autoHeight: true,
        field: 'title',
        cellStyle: { fontSize: '12px' },
        flex: 1,
    },
    {
        headerName: 'IUD',
        field: 'iud',
        width: 60,
        cellStyle: { fontSize: '12px', textAlign: 'center' },
    },
    {
        headerName: 'loader',
        field: 'loader',
        width: 130,
        cellStyle: { fontSize: '12px', textAlign: 'center' },
        cellRendererFramework: (params) => {
            return <RcvProgsRenderer {...params} onClick={params.data.handleClickValue} />;
        },
    },
    {
        headerName: 'dump',
        field: 'dump',
        width: 130,
        cellStyle: { fontSize: '12px', textAlign: 'center' },
        cellRendererFramework: (params) => {
            return <RcvProgsRenderer {...params} onClick={params.data.handleClickValue} />;
        },
    },
    {
        headerName: 'sender',
        field: 'sender',
        cellStyle: { fontSize: '12px' },
        children: [
            {
                headerName: '네이버',
                field: 'naver',
                width: 130,
                cellStyle: { fontSize: '12px', textAlign: 'center' },
                cellRendererFramework: (params) => {
                    return <RcvProgsRenderer {...params} onClick={params.data.handleClickValue} />;
                },
            },
            {
                headerName: '다음',
                field: 'daum',
                width: 130,
                cellStyle: { fontSize: '12px', textAlign: 'center' },
                cellRendererFramework: (params) => {
                    return <RcvProgsRenderer {...params} onClick={params.data.handleClickValue} />;
                },
            },
            {
                headerName: '네이트',
                field: 'nate',
                width: 130,
                cellStyle: { fontSize: '12px', textAlign: 'center' },
                cellRendererFramework: (params) => {
                    return <RcvProgsRenderer {...params} onClick={params.data.handleClickValue} />;
                },
            },
            {
                headerName: '줌',
                field: 'zoom',
                width: 130,
                cellStyle: { fontSize: '12px', textAlign: 'center' },
                cellRendererFramework: (params) => {
                    return <RcvProgsRenderer {...params} onClick={params.data.handleClickValue} />;
                },
            },
        ],
    },
];

export const list = [
    {
        source: '중앙일보',
        seqNo: '70800',
        title: '테스트 기사 제목',
        iud: 'I',
        loader: '실패',
        loaderDt: null,
        dump: '대기',
        dumpDt: null,
        naver: '대기',
        naverDt: null,
        daum: '대기',
        daumDt: null,
        nate: '대기',
        nateDt: null,
        zoom: '대기',
        zoomDt: null,
    },
    {
        source: '선데이',
        seqNo: '70799',
        title: '테스트 기사 제목',
        iud: 'U',
        loader: '완료',
        loaderDt: '(2021-01-07 14:14:32)',
        dump: '완료',
        dumpDt: '(2021-01-07 14:14:32)',
        naver: '대기',
        naverDt: null,
        daum: '완료',
        daumDt: '(2021-01-07 14:14:32)',
        nate: '완료',
        nateDt: '(2021-01-07 14:14:32)',
        zoom: '대기',
        zoomDt: null,
    },
    {
        source: '일간',
        seqNo: '70798',
        title: '테스트 기사 제목',
        iud: 'I',
        loader: '대기',
        loaderDt: null,
        dump: '대기',
        dumpDt: null,
        naver: '대기',
        naverDt: null,
        daum: '대기',
        daumDt: null,
        nate: '대기',
        nateDt: null,
        zoom: '대기',
        zoomDt: null,
    },
    {
        source: '중앙데일리',
        seqNo: '70564',
        title: '테스트 기사 제목',
        iud: 'U',
        loader: '완료',
        loaderDt: '(2021-01-10 14:14:32)',
        dump: '완료',
        dumpDt: '(2021-01-10 14:14:32)',
        naver: '완료',
        naverDt: '(2021-01-10 14:14:32)',
        daum: '완료',
        daumDt: '(2021-01-10 14:14:32)',
        nate: '대기',
        nateDt: null,
        zoom: '대기',
        zoomDt: null,
    },
    {
        source: '중앙일보',
        seqNo: '70135',
        title: '테스트 기사 제목',
        iud: 'I',
        loader: '대기',
        loaderDt: null,
        dump: '실패',
        dumpDt: null,
        naver: '완료',
        naverDt: '(2021-01-10 17:11:10)',
        daum: '대기',
        daumDt: null,
        nate: '대기',
        nateDt: null,
        zoom: '대기',
        zoomDt: null,
    },
    {
        source: '선데이',
        seqNo: '70647',
        title: '테스트 기사 제목',
        iud: 'I',
        loader: '대기',
        loaderDt: null,
        dump: '실패',
        dumpDt: null,
        naver: '완료',
        naverDt: '(2021-01-09 15:14:32)',
        daum: '실패',
        daumDt: null,
        nate: '대기',
        nateDt: null,
        zoom: '완료',
        zoomDt: '(2021-01-09 15:14:32)',
    },
    {
        source: '일간',
        seqNo: '70670',
        title: '테스트 기사 제목',
        iud: 'I',
        loader: '완료',
        loaderDt: '(2021-01-18 17:18:08)',
        dump: '대기',
        dumpDt: null,
        naver: '대기',
        naverDt: null,
        daum: '대기',
        daumDt: null,
        nate: '실패',
        nateDt: null,
        zoom: '실패',
        zoomDt: null,
    },
    {
        source: '중앙데일리',
        seqNo: '70501',
        title: '테스트 기사 제목',
        iud: 'I',
        loader: '완료',
        loaderDt: '(2021-01-15 16:17:21)',
        dump: '실패',
        dumpDt: null,
        naver: '대기',
        naverDt: null,
        daum: '실패',
        daumDt: null,
        nate: '실패',
        nateDt: null,
        zoom: '완료',
        zoomDt: '(2021-01-15 16:15:23)',
    },
];
